from __future__ import annotations

_ZH_LABELS = {
    "date": "日期",
    "equity": "权益",
    "daily_return": "单期收益",
    "holdings": "持仓",
    "symbol": "代码",
    "shares": "股数",
    "price": "价格",
    "market_value": "市值",
    "weight": "权重",
    "cash": "现金",
    "total_equity": "总权益",
    "side": "方向",
    "target_shares": "目标股数",
    "gross_value": "成交金额",
    "commission": "佣金",
    "slippage": "滑点",
    "fixed_slippage": "固定滑点",
    "market_impact": "市场冲击",
    "transfer_fee": "过户费",
    "stamp_duty": "印花税",
    "cash_change": "现金变化",
    "reason": "原因",
    "momentum": "动量",
    "mean_reversion": "均值回归",
    "low_volatility": "低波动",
    "normalized_momentum": "标准化动量",
    "normalized_mean_reversion": "标准化均值回归",
    "normalized_low_volatility": "标准化低波动",
    "total_score": "总分",
    "selected": "入选",
    "benchmark_equity": "基准权益",
    "benchmark_daily_return": "基准单期收益",
    "excess_daily_return": "超额单期收益",
    "buy_turnover": "买入换手",
    "sell_turnover": "卖出换手",
    "turnover": "总换手",
    "cost": "交易成本",
    "metric": "指标代码",
    "label": "指标名称",
    "value": "数值",
    "total_return": "总收益",
    "annualized_return": "年化收益",
    "max_drawdown": "最大回撤",
    "volatility": "波动率",
    "downside_volatility": "下行波动率",
    "sharpe": "夏普比率",
    "sortino": "索提诺比率",
    "calmar": "卡玛比率",
    "win_rate": "胜率",
    "average_turnover": "平均换手",
    "total_cost": "总成本",
    "health_score": "策略健康评分",
    "health_grade": "策略健康等级",
    "gate_status": "策略闸门状态",
    "gate_failures": "策略闸门失败数",
    "health_warnings": "策略预警数",
    "critical_warnings": "严重预警数",
    "failed_gate_count": "失败闸门数",
    "primary_failed_gate_category": "主要失败闸门类别",
    "primary_failed_gate_name": "主要失败闸门",
    "failed_gate_summary": "失败闸门摘要",
    "matches_recommended_parameters": "匹配推荐参数",
    "recommended_parameter_mismatch": "推荐参数差异",
    "periods": "周期数",
    "benchmark_total_return": "基准总收益",
    "benchmark_annualized_return": "基准年化收益",
    "benchmark_volatility": "基准波动率",
    "benchmark_max_drawdown": "基准最大回撤",
    "excess_return": "超额收益",
    "tracking_error": "跟踪误差",
    "information_ratio": "信息比率",
    "beta": "Beta",
    "daily_alpha": "日度Alpha",
    "annualized_alpha": "年化Alpha",
    "correlation": "相关系数",
    "r_squared": "R平方",
    "run_id": "内部编号",
    "scheme_label": "方案编号",
    "output_dir": "输出目录",
    "rank": "名次",
    "initial_cash": "初始资金",
    "top_n": "持仓数量TopN",
    "selection_mode": "选股方向",
    "score_source": "评分来源",
    "lot_size": "每手股数",
    "max_group_positions": "单组最多入选数",
    "rebalance_every_n_days": "调仓间隔天数",
    "lookback_momentum": "动量回看窗口",
    "lookback_mean_reversion": "均值回归回看窗口",
    "lookback_volatility": "波动率回看窗口",
    "rolling_risk_window": "滚动风险窗口",
    "max_allowed_drawdown": "闸门最大回撤",
    "max_allowed_daily_var": "闸门最大日VaR",
    "min_allowed_rolling_return": "闸门最差滚动收益",
    "min_allowed_information_ratio": "闸门最低信息比率",
    "min_allowed_fill_rate": "闸门最低成交率",
    "min_allowed_execution_price_coverage": "闸门最低执行价覆盖率",
    "min_allowed_factor_score_coverage": "闸门最低外部评分覆盖率",
    "max_allowed_position_weight": "闸门最大单票权重",
    "max_allowed_group_weight": "闸门最大分组权重",
    "max_allowed_attribution_residual": "闸门最大归因残差",
    "commission_rate": "佣金率",
    "buy_commission_rate": "买入佣金率",
    "sell_commission_rate": "卖出佣金率",
    "slippage_rate": "滑点率",
    "market_impact_coefficient": "冲击成本系数",
    "market_impact_exponent": "冲击成本指数",
    "stamp_duty_rate": "印花税率",
    "min_commission": "最低佣金",
    "transfer_fee_rate": "过户费率",
    "target_cash_weight": "目标现金权重",
    "max_position_weight": "单票目标权重上限",
    "limit_up_down_rate": "涨跌停阈值",
    "st_limit_up_down_rate": "ST涨跌停阈值",
    "growth_limit_up_down_rate": "成长板涨跌停阈值",
    "bse_limit_up_down_rate": "北交所涨跌停阈值",
    "infer_limit_rate_by_symbol": "按代码推断涨跌停",
    "max_volume_participation": "最大成交量参与率",
    "infer_limit_flags": "自动推断涨跌停",
    "forward_fill_suspended_bars": "缺失行情前值停牌估值",
    "price_field": "价格字段",
    "start_date": "开始日期",
    "end_date": "结束日期",
    "equity_curve_csv": "净值曲线CSV",
    "config_effective_json": "最终生效配置JSON",
    "config_sources_json": "配置来源JSON",
    "run_manifest_json": "运行清单JSON",
    "equity_curve_svg": "净值曲线图",
    "positions_csv": "每日持仓账本CSV",
    "trades_csv": "逐笔交易明细CSV",
    "trade_attempts_csv": "未成交原因CSV",
    "factor_scores_csv": "因子评分明细CSV",
    "factor_ic_csv": "因子IC分析CSV",
    "factor_ic_json": "因子IC分析JSON",
    "factor_group_returns_csv": "因子分组收益CSV",
    "factor_group_returns_json": "因子分组收益JSON",
    "factor_decay_csv": "因子衰减分析CSV",
    "factor_decay_json": "因子衰减分析JSON",
    "factor_correlation_csv": "因子相关性矩阵CSV",
    "factor_correlation_json": "因子相关性矩阵JSON",
    "drawdown_csv": "回撤序列CSV",
    "drawdown_json": "回撤序列JSON",
    "monthly_returns_csv": "月度收益CSV",
    "monthly_returns_json": "月度收益JSON",
    "rolling_risk_csv": "滚动风险CSV",
    "rolling_risk_json": "滚动风险JSON",
    "relative_performance_csv": "相对基准表现CSV",
    "relative_performance_json": "相对基准表现JSON",
    "execution_quality_csv": "执行质量CSV",
    "execution_quality_json": "执行质量JSON",
    "exposure_csv": "持仓暴露CSV",
    "exposure_json": "持仓暴露JSON",
    "group_exposure_csv": "分组暴露CSV",
    "group_exposure_json": "分组暴露JSON",
    "return_attribution_csv": "收益归因CSV",
    "return_attribution_json": "收益归因JSON",
    "cost_attribution_csv": "成本归因CSV",
    "cost_attribution_json": "成本归因JSON",
    "pnl_ledger_csv": "盈亏对账CSV",
    "pnl_ledger_json": "盈亏对账JSON",
    "strategy_health_csv": "策略健康诊断CSV",
    "strategy_health_gates_csv": "策略风险闸门CSV",
    "strategy_health_json": "策略健康诊断JSON",
    "rebalance_log_csv": "调仓日志CSV",
    "performance_summary_csv": "绩效汇总CSV",
    "performance_summary_json": "绩效汇总JSON",
    "report_html": "单次回测报告",
    "batch_summary_csv": "参数扫描汇总CSV",
    "batch_summary_json": "参数扫描汇总JSON",
    "batch_leaderboard_csv": "最优结果排行CSV",
    "batch_leaderboard_json": "最优结果排行JSON",
    "best_run_json": "最佳方案JSON",
    "batch_chart_svg": "参数对比图",
    "batch_heatmap_svg": "参数热力图",
    "batch_stability_csv": "参数稳定性CSV",
    "batch_stability_json": "参数稳定性JSON",
    "parameter_sensitivity_csv": "参数敏感度CSV",
    "walk_forward_csv": "Walk-forward汇总CSV",
    "walk_forward_json": "Walk-forward汇总JSON",
    "walk_forward_report_html": "Walk-forward报告",
    "walk_forward_optimization_csv": "Walk-forward优化CSV",
    "walk_forward_optimization_json": "Walk-forward优化JSON",
    "walk_forward_optimization_report_html": "Walk-forward优化报告",
}

_HUMAN_READABLE_ENCODING = "utf-8-sig"

_METRIC_EXPLANATIONS = {
    "total_return": "总收益 = 期末权益 / 期初权益 - 1。",
    "annualized_return": "按 252 个交易日折算后的年化收益率。",
    "max_drawdown": "历史净值从阶段高点回落的最大幅度。",
    "volatility": "组合日收益率折算后的年化波动率。",
    "downside_volatility": "仅统计下跌收益后的年化波动率。",
    "sharpe": "年化平均超额收益与总波动率之比。",
    "sortino": "年化收益与下行波动率之比。",
    "calmar": "年化收益与最大回撤绝对值之比。",
    "win_rate": "收益为正的周期占全部周期的比例。",
    "average_turnover": "每次调仓的平均换手比例。",
    "total_cost": "全部调仓累计产生的交易成本。",
    "periods": "本次回测实际计算的收益周期数量。",
    "benchmark_total_return": "基准从期初到期末的总收益。",
    "benchmark_annualized_return": "基准按 252 个交易日折算后的年化收益率。",
    "benchmark_volatility": "基准日收益率折算后的年化波动率。",
    "benchmark_max_drawdown": "基准净值从阶段高点回落的最大幅度。",
    "excess_return": "组合总收益减去基准总收益。",
    "tracking_error": "组合相对基准的超额收益波动率。",
    "information_ratio": "平均超额收益与跟踪误差之比。",
    "beta": "组合日收益相对基准日收益的市场暴露。",
    "annualized_alpha": "在零无风险利率口径下，剔除 beta 暴露后的年化超额收益。",
    "r_squared": "基准日收益解释组合日收益波动的比例。",
}

_DEFAULT_A_SHARE_SYMBOL_NAMES = {
    "000001": "平安银行",
    "600036": "招商银行",
    "600519": "贵州茅台",
    "601318": "中国平安",
    "300750": "宁德时代",
}



def display_label(key: str) -> str:
    return f"{chinese_label(key)} / {key}"


def chinese_label(key: str) -> str:
    if key.startswith("param_"):
        param_name = key.removeprefix("param_")
        return f"参数_{chinese_label(param_name)}"
    return _ZH_LABELS.get(key, key)


def metric_explanation(key: str) -> str:
    return _METRIC_EXPLANATIONS.get(key, "")


def format_symbol(symbol: str, symbol_names: dict[str, str] | None = None) -> str:
    if symbol_names and symbol in symbol_names:
        return f"{symbol}（{symbol_names[symbol]}）"
    if symbol in _DEFAULT_A_SHARE_SYMBOL_NAMES:
        return f"{symbol}（{_DEFAULT_A_SHARE_SYMBOL_NAMES[symbol]}）"
    return symbol
